name: Triangle Identifier Workflow

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file"

      - name: Run Triangle Test File
        run: |
          python -m unittest Triangle_Project\triangle_testUnits.py
